/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedPlaygroundRouteRouteImport } from './routes/_authenticated/playground/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicAdminRouteImport } from './routes/_public/admin'
import { Route as AuthenticatedPlaygroundPresenceRouteImport } from './routes/_authenticated/playground/presence'
import { Route as AuthenticatedPlaygroundStreamsRouteImport } from './routes/_authenticated/playground/streams'
import { Route as AuthenticatedServersIndexRouteImport } from './routes/_authenticated/servers/index'
import { Route as AuthenticatedServersNewRouteImport } from './routes/_authenticated/servers/new'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlaygroundRouteRoute =
  AuthenticatedPlaygroundRouteRouteImport.update({
    id: '/playground',
    path: '/playground',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAdminRoute = PublicAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedPlaygroundPresenceRoute =
  AuthenticatedPlaygroundPresenceRouteImport.update({
    id: '/presence',
    path: '/presence',
    getParentRoute: () => AuthenticatedPlaygroundRouteRoute,
  } as any)
const AuthenticatedPlaygroundStreamsRoute =
  AuthenticatedPlaygroundStreamsRouteImport.update({
    id: '/streams',
    path: '/streams',
    getParentRoute: () => AuthenticatedPlaygroundRouteRoute,
  } as any)
const AuthenticatedServersIndexRoute =
  AuthenticatedServersIndexRouteImport.update({
    id: '/servers/',
    path: '/servers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServersNewRoute = AuthenticatedServersNewRouteImport.update({
  id: '/servers/new',
  path: '/servers/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/playground': typeof AuthenticatedPlaygroundRouteRouteWithChildren
  '/admin': typeof PublicAdminRoute
  '/playground/presence': typeof AuthenticatedPlaygroundPresenceRoute
  '/playground/streams': typeof AuthenticatedPlaygroundStreamsRoute
  '/servers/new': typeof AuthenticatedServersNewRoute
  '/servers/': typeof AuthenticatedServersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/playground': typeof AuthenticatedPlaygroundRouteRouteWithChildren
  '/admin': typeof PublicAdminRoute
  '/playground/presence': typeof AuthenticatedPlaygroundPresenceRoute
  '/playground/streams': typeof AuthenticatedPlaygroundStreamsRoute
  '/servers/new': typeof AuthenticatedServersNewRoute
  '/servers': typeof AuthenticatedServersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/playground': typeof AuthenticatedPlaygroundRouteRouteWithChildren
  '/_public/admin': typeof PublicAdminRoute
  '/_public/': typeof PublicIndexRoute
  '/_authenticated/playground/presence': typeof AuthenticatedPlaygroundPresenceRoute
  '/_authenticated/playground/streams': typeof AuthenticatedPlaygroundStreamsRoute
  '/_authenticated/servers/new': typeof AuthenticatedServersNewRoute
  '/_authenticated/servers/': typeof AuthenticatedServersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/playground'
    | '/admin'
    | '/playground/presence'
    | '/playground/streams'
    | '/servers/new'
    | '/servers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/playground'
    | '/admin'
    | '/playground/presence'
    | '/playground/streams'
    | '/servers/new'
    | '/servers'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/playground'
    | '/_public/admin'
    | '/_public/'
    | '/_authenticated/playground/presence'
    | '/_authenticated/playground/streams'
    | '/_authenticated/servers/new'
    | '/_authenticated/servers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/playground': {
      id: '/_authenticated/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof AuthenticatedPlaygroundRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/admin': {
      id: '/_public/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof PublicAdminRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/playground/presence': {
      id: '/_authenticated/playground/presence'
      path: '/presence'
      fullPath: '/playground/presence'
      preLoaderRoute: typeof AuthenticatedPlaygroundPresenceRouteImport
      parentRoute: typeof AuthenticatedPlaygroundRouteRoute
    }
    '/_authenticated/playground/streams': {
      id: '/_authenticated/playground/streams'
      path: '/streams'
      fullPath: '/playground/streams'
      preLoaderRoute: typeof AuthenticatedPlaygroundStreamsRouteImport
      parentRoute: typeof AuthenticatedPlaygroundRouteRoute
    }
    '/_authenticated/servers/': {
      id: '/_authenticated/servers/'
      path: '/servers'
      fullPath: '/servers/'
      preLoaderRoute: typeof AuthenticatedServersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/servers/new': {
      id: '/_authenticated/servers/new'
      path: '/servers/new'
      fullPath: '/servers/new'
      preLoaderRoute: typeof AuthenticatedServersNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedPlaygroundRouteRouteChildren {
  AuthenticatedPlaygroundPresenceRoute: typeof AuthenticatedPlaygroundPresenceRoute
  AuthenticatedPlaygroundStreamsRoute: typeof AuthenticatedPlaygroundStreamsRoute
}

const AuthenticatedPlaygroundRouteRouteChildren: AuthenticatedPlaygroundRouteRouteChildren =
  {
    AuthenticatedPlaygroundPresenceRoute: AuthenticatedPlaygroundPresenceRoute,
    AuthenticatedPlaygroundStreamsRoute: AuthenticatedPlaygroundStreamsRoute,
  }

const AuthenticatedPlaygroundRouteRouteWithChildren =
  AuthenticatedPlaygroundRouteRoute._addFileChildren(
    AuthenticatedPlaygroundRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedPlaygroundRouteRoute: typeof AuthenticatedPlaygroundRouteRouteWithChildren
  AuthenticatedServersNewRoute: typeof AuthenticatedServersNewRoute
  AuthenticatedServersIndexRoute: typeof AuthenticatedServersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPlaygroundRouteRoute:
    AuthenticatedPlaygroundRouteRouteWithChildren,
  AuthenticatedServersNewRoute: AuthenticatedServersNewRoute,
  AuthenticatedServersIndexRoute: AuthenticatedServersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicAdminRoute: typeof PublicAdminRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAdminRoute: PublicAdminRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
