#!/usr/bin/env bun
/// <reference types="bun" />

/**
 * Lean local TLS for Vite only (HTTP/2 → no 6-connection HTTP/1.1 cap for StreamDB).
 * No Caddy, no Docker. Idempotent: skips openssl when certs already exist.
 */

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { run } from "../utils/run";

const ROOT = process.cwd();
const CERT_DIR = join(ROOT, "certs");

const ROOT_CRT = join(CERT_DIR, "vite-dev-root.crt");
const ROOT_KEY = join(CERT_DIR, "vite-dev-root.key");
const LEAF_CRT = join(CERT_DIR, "vite-dev.crt");
const LEAF_KEY = join(CERT_DIR, "vite-dev.key");
const LEAF_CSR = join(CERT_DIR, "vite-dev.csr");
const OPENSSL_CFG = join(CERT_DIR, "vite-dev-openssl.cnf");

const OPENSSL_CFG_CONTENT = `# Vite local HTTPS (generated by scripts/stack/setup-dev.ts)
[ req ]
default_bits       = 2048
prompt             = no
default_md         = sha256
distinguished_name = dn
req_extensions     = v3_req

[ dn ]
C=US
ST=Local
L=Dev
O=monrep
CN=localhost

[ v3_req ]
subjectAltName = @alt_names
keyUsage = digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth

[ alt_names ]
DNS.1 = localhost
IP.1 = 127.0.0.1
IP.2 = ::1
`;

mkdirSync(CERT_DIR, { recursive: true });
writeFileSync(OPENSSL_CFG, OPENSSL_CFG_CONTENT, "utf8");

// -------------------------
// Generate cert if missing
// -------------------------
const rootMissing = !existsSync(ROOT_CRT) || !existsSync(ROOT_KEY);
if (rootMissing) {
  console.log("\n🔐 Generating Vite local root CA...");
  run(["openssl", "genrsa", "-out", ROOT_KEY, "4096"]);
  run([
    "openssl",
    "req",
    "-x509",
    "-new",
    "-nodes",
    "-key",
    ROOT_KEY,
    "-sha256",
    "-days",
    "3650",
    "-out",
    ROOT_CRT,
    "-subj",
    "/C=US/ST=Local/L=Dev/O=monrep/CN=monrep Vite Dev Root CA",
  ]);
} else {
  console.log("✅ Vite local root CA already exists");
}

// -------------------------
// Generate leaf cert for localhost
// -------------------------
const leafMissing = !existsSync(LEAF_CRT) || !existsSync(LEAF_KEY);
if (leafMissing || rootMissing) {
  console.log("\n🔐 Generating Vite localhost leaf cert...");
  run(["openssl", "genrsa", "-out", LEAF_KEY, "2048"]);
  run(["openssl", "req", "-new", "-key", LEAF_KEY, "-out", LEAF_CSR, "-config", OPENSSL_CFG]);
  run([
    "openssl",
    "x509",
    "-req",
    "-in",
    LEAF_CSR,
    "-CA",
    ROOT_CRT,
    "-CAkey",
    ROOT_KEY,
    "-CAcreateserial",
    "-out",
    LEAF_CRT,
    "-days",
    "825",
    "-sha256",
    "-extfile",
    OPENSSL_CFG,
    "-extensions",
    "v3_req",
  ]);
} else {
  console.log("✅ Vite localhost leaf cert already exists");
}

if (process.platform === "darwin") {
  console.log("\n🔑 Trusting root CA in macOS System keychain (sudo)...");
  try {
    run([
      "sudo",
      "security",
      "add-trusted-cert",
      "-d",
      "-r",
      "trustRoot",
      "-k",
      "/Library/Keychains/System.keychain",
      ROOT_CRT,
    ]);
  } catch {
    console.warn(
      "⚠️  Could not trust cert automatically. Open certs/vite-dev-root.crt and trust it manually.",
    );
  }
} else {
  console.log(
    "\nℹ️  Non-macOS: trust certs/vite-dev-root.crt in your OS/browser if you want a quiet HTTPS prompt.",
  );
}

console.log("\n✅ Vite HTTPS certs ready under certs/");
console.log("   bun run --cwd packages/main dev  →  https://localhost:5274\n");
