#!/usr/bin/env bun
/// <reference types="bun" />

/**
 * Per-deploy brand: brand.json (gitignored). Template: brand.json.example.
 * Run: bun run sync:brand
 *
 * If brand.json is missing, copies brand.json.example first.
 *
 * Writes:
 * - packages/main/src/brand.gen.ts
 * - packages/agent/src/brand.gen.rs
 * - scripts/install-agent.sh (from install-agent.sh.tpl)
 * - packages/main/src/server/installSh.gen.ts
 */

import { copyFileSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { renderTemplate } from "./pkg/template-render";

const REPO_ROOT = process.cwd();
const BRAND_PATH = join(REPO_ROOT, "brand.json");
const BRAND_EXAMPLE_PATH = join(REPO_ROOT, "brand.json.example");

type Brand = {
  productName: string;
  binName: string;
  githubOwner: string;
  githubRepo: string;
  controlPlaneOrigin: string;
  canonicalAppHost: string;
  marketingOrigins: Array<string>;
  installPath: string;
  releaseAssetPrefix: string;
  adminEmailDomain: string;
};

if (!existsSync(BRAND_PATH)) {
  if (!existsSync(BRAND_EXAMPLE_PATH)) {
    throw new Error("missing brand.json and brand.json.example — cannot sync brand");
  }
  copyFileSync(BRAND_EXAMPLE_PATH, BRAND_PATH);
  console.log("copied brand.json.example → brand.json (edit for your deploy)");
}

const brand = JSON.parse(readFileSync(BRAND_PATH, "utf8")) as Brand;

const githubRepo = `${brand.githubOwner}/${brand.githubRepo}`;
const controlPlaneOrigin = brand.controlPlaneOrigin.replace(/\/$/, "");
const installPath = `/${brand.installPath.replace(/^\/+|\/+$/g, "")}`;
const installUrl = `${controlPlaneOrigin}${installPath}`;
const installCommand = `curl -fsSL ${installUrl} | bash`;
const githubUrl = `https://github.com/${githubRepo}`;
const canonicalOrigin = `https://${brand.canonicalAppHost}`;

const frameAncestors = [
  "'self'",
  ...brand.marketingOrigins,
  canonicalOrigin,
  "http://localhost:5273",
  "http://127.0.0.1:5273",
  "https://localhost:5273",
  "https://127.0.0.1:5273",
];

function write(rel: string, content: string) {
  const path = join(REPO_ROOT, rel);
  writeFileSync(path, content);
  console.log(`wrote ${rel}`);
}

write(
  "packages/main/src/brand.gen.ts",
  `/* AUTO-GENERATED by scripts/sync-brand.ts — edit brand.json, then bun run sync:brand */

export const PRODUCT_NAME = ${JSON.stringify(brand.productName)} as const;
export const BIN_NAME = ${JSON.stringify(brand.binName)} as const;
export const GITHUB_OWNER = ${JSON.stringify(brand.githubOwner)} as const;
export const GITHUB_REPO_NAME = ${JSON.stringify(brand.githubRepo)} as const;
export const GITHUB_REPO = ${JSON.stringify(githubRepo)} as const;
export const GITHUB_URL = ${JSON.stringify(githubUrl)} as const;
export const CONTROL_PLANE_ORIGIN = ${JSON.stringify(controlPlaneOrigin)} as const;
export const CANONICAL_HOST = ${JSON.stringify(brand.canonicalAppHost)} as const;
export const CANONICAL_ORIGIN = ${JSON.stringify(canonicalOrigin)} as const;
export const MARKETING_ORIGINS = ${JSON.stringify(brand.marketingOrigins)} as const;
export const INSTALL_PATH = ${JSON.stringify(installPath)} as const;
export const INSTALL_URL = ${JSON.stringify(installUrl)} as const;
export const INSTALL_COMMAND = ${JSON.stringify(installCommand)} as const;
export const RELEASE_ASSET_PREFIX = ${JSON.stringify(brand.releaseAssetPrefix)} as const;
export const ADMIN_EMAIL_DOMAIN = ${JSON.stringify(brand.adminEmailDomain)} as const;
export const FRAME_ANCESTORS = ${JSON.stringify(frameAncestors)} as const;
`,
);

write(
  "packages/agent/src/brand.gen.rs",
  `// AUTO-GENERATED by scripts/sync-brand.ts — edit brand.json, then bun run sync:brand

#[allow(dead_code, reason = "brand SSOT; not every constant is wired yet")]
pub const PRODUCT_NAME: &str = ${JSON.stringify(brand.productName)};
#[allow(dead_code, reason = "brand SSOT; not every constant is wired yet")]
pub const BIN_NAME: &str = ${JSON.stringify(brand.binName)};
pub const RELEASE_REPO: &str = ${JSON.stringify(githubRepo)};
#[allow(dead_code, reason = "brand SSOT; not every constant is wired yet")]
pub const CONTROL_PLANE_ORIGIN: &str = ${JSON.stringify(controlPlaneOrigin)};
#[allow(dead_code, reason = "brand SSOT; not every constant is wired yet")]
pub const RELEASE_ASSET_PREFIX: &str = ${JSON.stringify(brand.releaseAssetPrefix)};
pub const RELEASE_ASSET_X86_64: &str = ${JSON.stringify(`${brand.releaseAssetPrefix}-x86_64`)};
pub const RELEASE_ASSET_AARCH64: &str = ${JSON.stringify(`${brand.releaseAssetPrefix}-aarch64`)};
`,
);

const installTpl = readFileSync(join(REPO_ROOT, "scripts/install-agent.sh.tpl"), "utf8");
const installSh = renderTemplate(installTpl, {
  productName: brand.productName,
  installUrl,
  githubRepo,
  binName: brand.binName,
  releaseAssetPrefix: brand.releaseAssetPrefix,
});

write("scripts/install-agent.sh", installSh);
write(
  "packages/main/src/server/installSh.gen.ts",
  `/* AUTO-GENERATED by scripts/sync-brand.ts — edit brand.json / install-agent.sh.tpl, then bun run sync:brand */
export const INSTALL_SH = ${JSON.stringify(installSh)};
`,
);

console.log("sync:brand ok");
